///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserRegisterModelCreateUserRoleRequest {
/*
{
  "roleName": 0,
  "expiresDate": "2022-09-06T09:49:36.102Z"
} 
*/

  int? roleName;
  String? expiresDate;

  UserRegisterModelCreateUserRoleRequest({
    this.roleName,
    this.expiresDate,
  });
  UserRegisterModelCreateUserRoleRequest.fromJson(Map<String, dynamic> json) {
    roleName = json['roleName']?.toInt();
    expiresDate = json['expiresDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roleName'] = roleName;
    data['expiresDate'] = expiresDate;
    return data;
  }
}

class UserRegisterModelCreatePhoneRequest {
/*
{
  "phoneNumber": "string"
} 
*/

  String? phoneNumber;

  UserRegisterModelCreatePhoneRequest({
    this.phoneNumber,
  });
  UserRegisterModelCreatePhoneRequest.fromJson(Map<String, dynamic> json) {
    phoneNumber = json['phoneNumber']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['phoneNumber'] = phoneNumber;
    return data;
  }
}

class UserRegisterModelCreateMailAddressRequest {
/*
{
  "mailAddress": "string"
} 
*/

  String? mailAddress;

  UserRegisterModelCreateMailAddressRequest({
    this.mailAddress,
  });
  UserRegisterModelCreateMailAddressRequest.fromJson(
      Map<String, dynamic> json) {
    mailAddress = json['mailAddress']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mailAddress'] = mailAddress;
    return data;
  }
}

class UserRegisterModelCreatePasswordRequest {
/*
{
  "password": "string",
  "passwordConfirm": "string"
} 
*/

  String? password;
  String? passwordConfirm;

  UserRegisterModelCreatePasswordRequest({
    this.password,
    this.passwordConfirm,
  });
  UserRegisterModelCreatePasswordRequest.fromJson(Map<String, dynamic> json) {
    password = json['password']?.toString();
    passwordConfirm = json['passwordConfirm']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['password'] = password;
    data['passwordConfirm'] = passwordConfirm;
    return data;
  }
}

class UserRegisterModel {
/*
{
  "clientId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "clientSecret": "string",
  "userName": "string",
  "firstName": "string",
  "lastName": "string",
  "birthDay": "2022-09-06T09:49:36.102Z",
  "createPasswordRequest": {
    "password": "string",
    "passwordConfirm": "string"
  },
  "createMailAddressRequest": {
    "mailAddress": "string"
  },
  "createPhoneRequest": {
    "phoneNumber": "string"
  },
  "createUserRoleRequest": [
    {
      "roleName": 0,
      "expiresDate": "2022-09-06T09:49:36.102Z"
    }
  ]
} 
*/

  String? clientId;
  String? clientSecret;
  String? userName;
  String? firstName;
  String? lastName;
  String? birthDay;
  UserRegisterModelCreatePasswordRequest? createPasswordRequest;
  UserRegisterModelCreateMailAddressRequest? createMailAddressRequest;
  UserRegisterModelCreatePhoneRequest? createPhoneRequest;
  List<UserRegisterModelCreateUserRoleRequest?>? createUserRoleRequest;

  UserRegisterModel({
    this.clientId,
    this.clientSecret,
    this.userName,
    this.firstName,
    this.lastName,
    this.birthDay,
    this.createPasswordRequest,
    this.createMailAddressRequest,
    this.createPhoneRequest,
    this.createUserRoleRequest,
  });
  UserRegisterModel.fromJson(Map<String, dynamic> json) {
    clientId = json['clientId']?.toString();
    clientSecret = json['clientSecret']?.toString();
    userName = json['userName']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    birthDay = json['birthDay']?.toString();
    createPasswordRequest = (json['createPasswordRequest'] != null)
        ? UserRegisterModelCreatePasswordRequest.fromJson(
            json['createPasswordRequest'])
        : null;
    createMailAddressRequest = (json['createMailAddressRequest'] != null)
        ? UserRegisterModelCreateMailAddressRequest.fromJson(
            json['createMailAddressRequest'])
        : null;
    createPhoneRequest = (json['createPhoneRequest'] != null)
        ? UserRegisterModelCreatePhoneRequest.fromJson(
            json['createPhoneRequest'])
        : null;
    if (json['createUserRoleRequest'] != null) {
      final v = json['createUserRoleRequest'];
      final arr0 = <UserRegisterModelCreateUserRoleRequest>[];
      v.forEach((v) {
        arr0.add(UserRegisterModelCreateUserRoleRequest.fromJson(v));
      });
      createUserRoleRequest = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['clientId'] = clientId;
    data['clientSecret'] = clientSecret;
    data['userName'] = userName;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['birthDay'] = birthDay;
    if (createPasswordRequest != null) {
      data['createPasswordRequest'] = createPasswordRequest!.toJson();
    }
    if (createMailAddressRequest != null) {
      data['createMailAddressRequest'] = createMailAddressRequest!.toJson();
    }
    if (createPhoneRequest != null) {
      data['createPhoneRequest'] = createPhoneRequest!.toJson();
    }
    if (createUserRoleRequest != null) {
      final v = createUserRoleRequest;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['createUserRoleRequest'] = arr0;
    }
    return data;
  }
}
